# Generated by Django 2.2.3 on 2019-08-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetContentpari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpari',
            name='datePari',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpari',
            name='idUser',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='userpari',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpari',
            name='idPari',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpari',
            name='montantParier',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='userpari',
            name='nameUser',
            field=models.CharField(default='XXXX', max_length=200),
        ),
    ]
